// DJANGO/Web1/angular-frontend/src/app/projects/projects.component.ts

import { Component, OnInit } from '@angular/core';
import { ProjectService } from '../project.service';

@Component({
    selector: 'app-projects',
    templateUrl: './projects.component.html',
    styleUrls: ['./projects.component.css']
})
export class ProjectsComponent implements OnInit {
    projects = [];

    constructor(private projectService: ProjectService) { }

    ngOnInit(): void {
        this.projectService.getProjects().subscribe(data => {
            this.projects = data;
        });
    }
}

<div class="projects-container">
    <div *ngFor="let project of projects" class="project-card">
        <img [src]="project.image" alt="{{project.title}}">
        <h3>{{project.title}}</h3>
        <p>{{project.description}}</p>
    </div>
</div>

// DJANGO/Web1/react-frontend/src/components/Projects.js
import React, { useEffect, useState } from 'react';
import { getProjects } from '../services/projectService';

const Projects = () => {
    const [projects, setProjects] = useState([]);

    useEffect(() => {
        const fetchProjects = async () => {
            const data = await getProjects();
            setProjects(data);
        };

        fetchProjects();
    }, []);

    return (
        <div className="projects-container">
            {projects.map(project => (
                <div key={project.id} className="project-card">
                    <img src={project.image} alt={project.title} />
                    <h3>{project.title}</h3>
                    <p>{project.description}</p>
                </div>
            ))}
        </div>
    );
};

export default Projects;
